/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ensino.mvc.view.main;

import ensino.mvc.view.listeners.MainActionListener;

/**
 *
 * @author nicho
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        initListeners();
    }
    
    private void initListeners() {
        MainActionListener mainListener = new MainActionListener(desktop);
        
        menuItemConfiguracao.addActionListener(mainListener);
        menuItemSair.addActionListener(mainListener);
        
        btConfig.addActionListener(mainListener);
        btCampus.addActionListener(mainListener);
        btCalendario.addActionListener(mainListener);
        btCursos.addActionListener(mainListener);
        btTurma.addActionListener(mainListener);
        btUnidadeCurricular.addActionListener(mainListener);
        btBibliografia.addActionListener(mainListener);
        
        btPlano.addActionListener(mainListener);
        
        btSair.addActionListener(mainListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        toolBar = new javax.swing.JToolBar();
        btConfig = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btCampus = new javax.swing.JButton();
        btCalendario = new javax.swing.JButton();
        btCursos = new javax.swing.JButton();
        btTurma = new javax.swing.JButton();
        btUnidadeCurricular = new javax.swing.JButton();
        btBibliografia = new javax.swing.JButton();
        toolBarPlanejamento = new javax.swing.JToolBar();
        btPlano = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btSair = new javax.swing.JButton();
        menuPrincipal = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuItemConfiguracao = new javax.swing.JMenuItem();
        menuItemNovo = new javax.swing.JMenuItem();
        separadorArquivo = new javax.swing.JPopupMenu.Separator();
        menuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktop.setAutoscrolls(true);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 938, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 673, Short.MAX_VALUE)
        );

        toolBar.setRollover(true);

        btConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/config-button-50px.png"))); // NOI18N
        btConfig.setText("Configurações");
        btConfig.setFocusable(false);
        btConfig.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btConfig.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btConfig);
        toolBar.add(jSeparator2);

        btCampus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/university-icon-50px.png"))); // NOI18N
        btCampus.setText("Campi");
        btCampus.setFocusable(false);
        btCampus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCampus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btCampus);

        btCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendar-image-png-50px.png"))); // NOI18N
        btCalendario.setText("Calendário");
        btCalendario.setToolTipText("");
        btCalendario.setFocusable(false);
        btCalendario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCalendario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btCalendario);

        btCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/courses-icon-50px.png"))); // NOI18N
        btCursos.setText("Cursos");
        btCursos.setFocusable(false);
        btCursos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCursos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btCursos);

        btTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/classroom-50px.png"))); // NOI18N
        btTurma.setText("Turma");
        btTurma.setToolTipText("");
        btTurma.setFocusable(false);
        btTurma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btTurma.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btTurma);

        btUnidadeCurricular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school-icon-50px.png"))); // NOI18N
        btUnidadeCurricular.setText("Und. Curricular");
        btUnidadeCurricular.setActionCommand("UnidadeCurricular");
        btUnidadeCurricular.setFocusable(false);
        btUnidadeCurricular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btUnidadeCurricular.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btUnidadeCurricular);

        btBibliografia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/library-icon-50px.png"))); // NOI18N
        btBibliografia.setText("Bibliografia");
        btBibliografia.setFocusable(false);
        btBibliografia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBibliografia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btBibliografia);

        toolBarPlanejamento.setRollover(true);

        btPlano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plano-icon-50px.png"))); // NOI18N
        btPlano.setText("Plano Ensino");
        btPlano.setActionCommand("PlanoEnsino");
        btPlano.setFocusable(false);
        btPlano.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPlano.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBarPlanejamento.add(btPlano);
        toolBarPlanejamento.add(jSeparator1);

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit-button-50px.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.setFocusable(false);
        btSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBarPlanejamento.add(btSair);

        menuArquivo.setActionCommand("Arquivo");
        menuArquivo.setLabel("Arquivo");

        menuItemConfiguracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/config-button-25px.png"))); // NOI18N
        menuItemConfiguracao.setLabel("Configurações");
        menuArquivo.add(menuItemConfiguracao);

        menuItemNovo.setLabel("Novo");
        menuArquivo.add(menuItemNovo);
        menuArquivo.add(separadorArquivo);

        menuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit-button-25px.png"))); // NOI18N
        menuItemSair.setLabel("Sair");
        menuArquivo.add(menuItemSair);

        menuPrincipal.add(menuArquivo);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toolBarPlanejamento, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toolBarPlanejamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktop))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            MainFrame m = new MainFrame();
            m.setLocationRelativeTo(null);
            m.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBibliografia;
    private javax.swing.JButton btCalendario;
    private javax.swing.JButton btCampus;
    private javax.swing.JButton btConfig;
    private javax.swing.JButton btCursos;
    private javax.swing.JButton btPlano;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btTurma;
    private javax.swing.JButton btUnidadeCurricular;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuItemConfiguracao;
    private javax.swing.JMenuItem menuItemNovo;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JPopupMenu.Separator separadorArquivo;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JToolBar toolBarPlanejamento;
    // End of variables declaration//GEN-END:variables
}
