/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ensino.configuracoes.view.frame;

import ensino.configuracoes.view.panels.TecnicaPanel;
import ensino.configuracoes.view.panels.LegendaPanel;
import ensino.configuracoes.view.panels.RecursoPanel;
import ensino.configuracoes.view.panels.InstrumentoAvaliacaoPanel;
import ensino.configuracoes.model.Campus;
import ensino.configuracoes.view.models.ConfiguracoesTreeModel;
import ensino.configuracoes.view.panels.DocentePanel;
import ensino.defaults.DefaultFormPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author nicho
 */
public class FrameConfiguracao extends javax.swing.JInternalFrame {

    private JPanel configuracaoCardPanel;
    // painel de legenda
    private DefaultFormPanel legendaPanel;
    // painel do recurso
    private DefaultFormPanel recursoPanel;
    // painel da técnica
    private DefaultFormPanel tecnicaPanel;
    // painel dos instrumentos de avaliação
    private DefaultFormPanel instrumentoPanel;
    // painel dos docentes
    private DefaultFormPanel docentePanel;

    /**
     * Creates new form frameConfiguracao
     */
    public FrameConfiguracao() {
        super("Configurações", true, true, true, true);
        initComponents();

        configuracaoCardPanel = new JPanel(new CardLayout());
        mainPanel.add(configuracaoCardPanel);
        // Adiciona um painel vazio
        JPanel panelNulo = new JPanel();
        panelNulo.setName("panel.nulo");
        configuracaoCardPanel.add(panelNulo, panelNulo.getName());

        // Controle da ficha do cadastro/manutenção de legenda
        legendaPanel = new LegendaPanel(this);
        configuracaoCardPanel.add(legendaPanel, legendaPanel.getName());

        // Controle da ficha do cadastro/manutenção do curso
        recursoPanel = new RecursoPanel(this);
        configuracaoCardPanel.add(recursoPanel, recursoPanel.getName());

        // Controle da ficha do cadastro/manutenção do curso
        tecnicaPanel = new TecnicaPanel(this);
        configuracaoCardPanel.add(tecnicaPanel, tecnicaPanel.getName());

        // Controle da ficha do cadastro/manutenção do curso
        instrumentoPanel = new InstrumentoAvaliacaoPanel(this);
        configuracaoCardPanel.add(instrumentoPanel, instrumentoPanel.getName());

        // Controle da ficha do cadastro/manutenção do docente
        docentePanel = new DocentePanel(this);
        configuracaoCardPanel.add(docentePanel, docentePanel.getName());

        // Organiza os dados na jtree
        estruturarArvoreDeConfiguracoes();
        // expande o JTree
        expandAllNodes(treeConfiguracoes, 0, treeConfiguracoes.getRowCount());
    }

    private void expandAllNodes(JTree tree, int startingIndex, int rowCount) {
        for (int i = startingIndex; i < rowCount; ++i) {
            tree.expandRow(i);
        }

        if (tree.getRowCount() != rowCount) {
            expandAllNodes(tree, rowCount, tree.getRowCount());
        }
    }

    private void estruturarArvoreDeConfiguracoes() {
        TreeSelectionModel tsm = treeConfiguracoes.getSelectionModel();
        tsm.setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);

        treeConfiguracoes.addTreeSelectionListener(new ConfiguracoesTreeSelectionListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        treePanel = new javax.swing.JPanel();
        scrollTree = new javax.swing.JScrollPane();
        treeConfiguracoes = new javax.swing.JTree();

        setTitle("Configurações");

        treeConfiguracoes.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        treeConfiguracoes.setModel(new ConfiguracoesTreeModel());
        treeConfiguracoes.setMaximumSize(new java.awt.Dimension(120, 64));
        scrollTree.setViewportView(treeConfiguracoes);

        javax.swing.GroupLayout treePanelLayout = new javax.swing.GroupLayout(treePanel);
        treePanel.setLayout(treePanelLayout);
        treePanelLayout.setHorizontalGroup(
            treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treePanelLayout.createSequentialGroup()
                .addComponent(scrollTree, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        treePanelLayout.setVerticalGroup(
            treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollTree, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(treePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(treePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane scrollTree;
    private javax.swing.JTree treeConfiguracoes;
    private javax.swing.JPanel treePanel;
    // End of variables declaration//GEN-END:variables

    private class ConfiguracoesTreeSelectionListener implements TreeSelectionListener {

        @Override
        public void valueChanged(TreeSelectionEvent e) {
            TreePath tp = e.getPath();
            CardLayout layout = (CardLayout) configuracaoCardPanel.getLayout();
            String lastPath = tp.getLastPathComponent().toString();
            // recuperar o nó superior para identificar o campus
            TreePath parent = tp.getParentPath();
            DefaultMutableTreeNode parentNode = (DefaultMutableTreeNode) parent.getLastPathComponent();
            Campus campus;
            switch (lastPath) {
                case "Legenda":
                    layout.show(configuracaoCardPanel, legendaPanel.getName());
                    break;
                case "Recurso":
                    layout.show(configuracaoCardPanel, recursoPanel.getName());
                    break;
                case "Técnica":
                    layout.show(configuracaoCardPanel, tecnicaPanel.getName());
                    break;
                case "Instrumento de Avaliação":
                    layout.show(configuracaoCardPanel, instrumentoPanel.getName());
                    break;
                case "Docente":
                    layout.show(configuracaoCardPanel, docentePanel.getName());
                    break;
                default:
                    layout.show(configuracaoCardPanel, "panel.nulo");
                    break;
            }
        }

    }
}
